### ISSUE TITLE
If I put 0 cars sold the share price is still $77

### ISSUE THREAD

**Issue by lucadellanna** [TashaARK/ARK-Invest-Tesla-Valuation-Model#16]
Clearly, I would expect that a correct model would output a share price of $0 with 0 cars sold.

You can reproduce this error by changing the value of cell G9 to 0.

More examples here: https://twitter.com/Keubiko/status/1132013468796805120

**Comment by jasonpiepmeier** [comment]
it assumes a liquidation value of the property, plant and equipment.  Tesla does have patents, IP, real estate, factories, brand name etc.  Those are not worth zero

**Comment by jasonpiepmeier** [comment]
if you follow the cells and formulas backwards from the $77 you can see how ARK arrived at it.  The $77 is net of debt.  It traces back to Row 19 in the model

**Comment by lucadellanna** [comment]
That would be true in a static analysis (neglecting that liquidation value is ab 20-40% of face value AFAIK).

In a dynamic one, if in an automotive company sales slow down and the capacity is not flexible, cash crunches occur. Working capital quickly turns negative. Debt increases. Restructuring might happen. Shares get a value of pennies on the dollar.

Now, I'm not saying that the model must consider bankruptcy. Though, by considering a "bear case", it perhaps should.

I'm saying that this model works under the strong assumption that the ramp up is permanent. Which is a very strong assumption, and should at least made explicit.

**Comment by lucadellanna** [comment]
But let's assume a static model is okay.

Current PPE is $10B according to the last 10-Q.
Further debt should be taken in order to reach a $17-19B 2023 PP&E.

This additional debt is nowhere to be seen in the model.

**Comment by jasonpiepmeier** [comment]
Those are good points.  I think it is unlikely that Tesla pays down that much debt, not because they wouldn't have the opportunity to do so based on enhanced cash flow (if either the bull or bear scenarios played out based on assumptions in model), but because Elon seems comfortable with debt and would likely use debt to fuel further growth into new business lines that don't even exist today.  Or use cash to buy back stock or pay a dividend like Apple has done once it got itself in a healthy financial position with excess cash flow. But as long as Elon is involved, and you don't have a "Tim Cook" type successor CEO, and you have a founder type visionary, I think they will funnel cash flow into new business lines that ARK can't possibly model because they don't exist today.  So based on the known items today, they assume some debt is paid off with cash flow rather than buybacks or dividends

**Comment by jasonpiepmeier** [comment]
As far as "bear case".  I think it is a definitional thing.  As a stock investor, what I would call my "worst case" scenario is always $0 and bankruptcy for any stock, but a "bear case" as ARK is using it, is just a case where not all of your good items come to pass, or take longer than expected.  The "worst case" scenario for Tesla, and every single stock that exists, is $0.  That's the risk of the stock market, and being an equity holder in any company.  ARK could certainly add more than just two scenarios to the model with more upside cases for energy storage/solar etc. and more downside scenarios as well.  There are nearly endless permutations as to what could transpire in the future

**Comment by lucadellanna** [comment]
It is true that ARK's bear case doesn't have to be a bankruptcy case nor the case a bear would make.
Almost 3x the current share price seems a bit bullish for anyone's bear case, though.

**Comment by jasonpiepmeier** [comment]
Well it is a 5-year target, whereas pretty much any sell-side analyst on Wall Street only gives a 1-year target.  And the stock is down almost 50% from $387.  The bear case of $560 is not a great 5-year CAGR from the 52-week high of $387.   From the 52-week high price of $387 it is only an 8% CAGR over 5-years.  From the current price of ~$190 it's only a 24% CAGR.  That's a good return, but not a crazy return.
